### ISSUE TITLE
Incorrect syntax highlighting for hash (#) in pretty format

### ISSUE THREAD

**Issue by jonny7read** [robballou/gitconfig-sublimetext#7]
As part of a git log pretty format, I have a property that sets custom colours using '%C(#9999FF)' which is a valid commad to set the colour. In sublime this is showing as a comment, since # is also the character used for comments. therefore there needs to be a condition, if possible, to only highlight text as a comment after a hash, _unless it follows an open bracket without a close bracket_.

Other than that, loving the package, so thank you!

**Comment by robballou** [comment]
Can you provide a sample of the config for testing? Thanks

**Comment by jonny7read** [comment]
Hey Rob,

I'll send you the full configuration tomorrow when I'm back at work (from
England so it's 8PM BST now).

Essentially though it includes the command '%C(#0000FF)' to set the colour
of some text to blue. Have a look at 'git log pretty format' in Google for
this and other examples.

Thanks,
Jonny
